import http from 'k6/http';
import { check } from 'k6';

export const BASE_URL = __ENV.BASE_URL || 'http://localhost:8081';

// Customer and merchant IDs match those generated by StandaloneTransactionController
export const CUSTOMERS = [
  'CUST-001', 'CUST-002', 'CUST-003', 'CUST-004', 'CUST-005',
  'CUST-006', 'CUST-007', 'CUST-008', 'CUST-009', 'CUST-010',
];

export const MERCHANTS = [
  'MERCH-WOOLWORTHS-ZA', 'MERCH-CHECKERS-ZA', 'MERCH-PICK-N-PAY-ZA',
  'MERCH-SHOPRITE-ZA', 'MERCH-CLICKS-ZA', 'MERCH-DISCHEM-ZA',
];

const HEADERS = { 'Content-Type': 'application/json' };

export function randomItem(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

export function randomAmount(min, max) {
  return parseFloat((Math.random() * (max - min) + min).toFixed(2));
}

// ── Write endpoints ──────────────────────────────────────────────────────────

export function submitTransaction(overrides = {}) {
  const payload = JSON.stringify({
    customerId:      overrides.customerId      || randomItem(CUSTOMERS),
    merchantId:      overrides.merchantId      || randomItem(MERCHANTS),
    amount:          overrides.amount          || randomAmount(10, 8000),
    currency:        'ZAR',
    category:        overrides.category        || 'RETAIL',
    transactionType: overrides.transactionType || 'CARD_NOT_PRESENT',
    location:        overrides.location        || 'Cape Town, ZA',
    latitude:        overrides.latitude        || -33.9249,
    longitude:       overrides.longitude       || 18.4241,
  });
  return http.post(`${BASE_URL}/api/v1/standalone/submit`, payload, { headers: HEADERS });
}

// Submits a transaction designed to trigger AMOUNT_THRESHOLD + HIGH_RISK_MERCHANT_CATEGORY
export function submitHighRiskTransaction(customerId) {
  return submitTransaction({
    customerId: customerId || randomItem(CUSTOMERS),
    amount:     randomAmount(6000, 15000),
    category:   'CRYPTO_EXCHANGE',
  });
}

export function patchOutcome(transactionId, outcome) {
  return http.patch(
    `${BASE_URL}/api/v1/transactions/${transactionId}/outcome`,
    JSON.stringify({ outcome }),
    { headers: HEADERS },
  );
}

// ── Read endpoints ───────────────────────────────────────────────────────────

export function getFlagged(params = {}) {
  return http.get(`${BASE_URL}/api/v1/transactions/flagged`, { params });
}

export function getPendingReview(params = {}) {
  return http.get(`${BASE_URL}/api/v1/transactions/pending-review`, { params });
}

export function getPassed(params = {}) {
  return http.get(`${BASE_URL}/api/v1/transactions/passed`, { params });
}

export function getAssessment(transactionId) {
  return http.get(`${BASE_URL}/api/v1/transactions/${transactionId}/assessment`);
}

export function getCustomerRisk(customerId) {
  return http.get(`${BASE_URL}/api/v1/customers/${customerId}/risk-summary`);
}

export function getMerchantFlagged(merchantId) {
  return http.get(`${BASE_URL}/api/v1/merchants/${merchantId}/flagged`);
}

export function getMerchantRisk(merchantId) {
  return http.get(`${BASE_URL}/api/v1/merchants/${merchantId}/risk-summary`);
}

export function getFraudSummary(params = {}) {
  return http.get(`${BASE_URL}/api/v1/stats/fraud-summary`, { params });
}

// ── Checks ───────────────────────────────────────────────────────────────────

export function checkOk(res) {
  return check(res, { 'status 200': (r) => r.status === 200 });
}

export function checkOkOrConflict(res) {
  return check(res, { 'status 200 or 409': (r) => r.status === 200 || r.status === 409 });
}
